apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: users-hpa-$ENV
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: users-deployment-$ENV
  minReplicas: 3
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: External
      external:
        metric:
          name: network_latency_ms
          selector:
            matchLabels:
              target: users-deployment-$ENV
        targetValue: 90
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: shilfs-hpa-$ENV
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shifts-deployment-$ENV
  minReplicas: 3
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: External
      external:
        metric:
          name: network_latency_ms
          selector:
            matchLabels:
              target: shifts-deployment-$ENV
        targetValue: 90

