apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: users-hpa-$ENV
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: users-$ENV
  minReplicas: 3
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Pods
      pods:
        metricName: users_network_latency_seconds
        targetAverageValue: 0.2
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: shilfs-hpa-$ENV
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shifts-$ENV
  minReplicas: 3
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Pods
      pods:
        metricName: shifts_network_latency_seconds
        targetAverageValue: 0.2
